name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  google_nav_bar: ^5.0.7
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
